### ISSUE TITLE
Symbols with leading unicode char are not supported

### ISSUE THREAD

**Issue by amkhlv** [rotty/lexpr-rs#112]
```
[dependencies]
lexpr = "0.2.7"
```

This program:
```
fn main() {
    let data = r#"(λ (x) y)"#;
    let v = lexpr::from_str(data).unwrap();
    println!("{:?}", v);
}
```
panics: `called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 2)`

Why ?

**Comment by rotty** [comment]
As it happens, unicode symbols are not (yet) supported. I hope to get energy and time to fix this in the near future.

Thanks for the bug report!
