### ISSUE TITLE
empty `HashMap` or struct { } cannot be deserialized properly

### ISSUE THREAD

**Issue by ijackson** [rotty/lexpr-rs#60]
Hi.  I have a project where I quite like the idea of using this instead of json.

But I discovered that with

```
enum Enum { Variant { } }
```
lexpr-rs serializes as `(Variant)` (which is good) but cannot deserialize.  Experimenting, it accepts `(Variant (Variant))` but that surely can't be intentional.

The first commit is a simple new test and probably not controversial, so I will make an MR of it.  The second demonstrates the problem, by failing the test.

Edit 24.7 01:03 UTC: This turns out to affect any empty map, including an empty HashMap.  #62 fixes this and adds some tests.

**Comment by rotty** [comment]
I think this should be resolved now that PR #62 is merged. Thanks for reporting!
