### ISSUE TITLE
Parsing number edge cases (kicad_pcb flavoured s-exp)

### ISSUE THREAD

**Issue by tachiniererin** [rotty/lexpr-rs#64]
I'm running into two cases regarding number parsing where i'm unsure how to proceed:

First is `(host pcbnew 5.1.6)`. This results in `5.1` as a float and `.6` as a string.

The second is `(tedit 5F199470)` and `(tstamp 5EFF45FA)` which are unix timestamps but without prefixes which would indicate the radix. All the other fields parse just fine in the file i tested, so it's just those three edge-cases.

I'm still learning rust and would like to implement this myself, but i'm unsure what the best approach would be to address this because both cases depend on the preceding tokens.

**Comment by rotty** [comment]
> I'm running into two cases regarding number parsing where i'm unsure how to proceed:
> 
> First is `(host pcbnew 5.1.6)`. This results in `5.1` as a float and `.6` as a string.
> 
What number should this parse as? A link to documentation describing `kicad_pcb` syntax would come in handy, if support for them should be added to `lexpr`.

> The second is `(tedit 5F199470)` and `(tstamp 5EFF45FA)` which are unix timestamps but without prefixes which would indicate the radix. All the other fields parse just fine in the file i tested, so it's just those three edge-cases.
> 
So does kicad use radix 16 (hexadecimal) by default?

> I'm still learning rust and would like to implement this myself, but i'm unsure what the best approach would be to address this because both cases depend on the preceding tokens.

It also depends on what other deviations from "regular" s-expression kicad syntax contains; I'd like to avoid incomplete support.

**Comment by tachiniererin** [comment]
The `5.1.6` should parse as a string, as it's not further defined what the version number format should look like. The only documentation there is as of now is unfortunately a bit outdated: https://en.wikibooks.org/wiki/Kicad/file_formats

The `tedit`, `tstamp` and `visible_elements` are the only cases where KiCad uses radix 16. The other numbers in the file i tried it with parse just fine. The only other hex number i encountered was with `(layerselection 0x010fc_ffffffff)`. Other numbers are all integers or floats which parse fine.

I'll try to build a minimal test case which should cover all the possible elements in a kicad_pcb file.

I have some very basic code here https://github.com/tachiniererin/lexpr-rs/commit/778b67b2d5d5a0c1078ae7edda5bf773c8da4abb where i tried to work around it. It's tested with this file: https://raw.githubusercontent.com/tachiniererin/kicad-rs/main/ferret.kicad_pcb

**Comment by tachiniererin** [comment]
I checked some more files and the linked documentation. The `layerselection` is the one thing where old (unknown, probably radix 10 integer) and new (hex format prefixed with 0x with underscore to separate lower 4 bytes) formats diverge. Apart from that I couldn't find any more syntax quirks apart from the ones already listed.

**Comment by eugenio** [comment]
Hello @rotty  and @tachiniererin,
what's the status of the kicad related code?
Is it merged yet ? Does it need further testing?

**Comment by tachiniererin** [comment]
The format has changed quite a bit in the meantime and the weird numbers aren't an issue anymore fortunately. Unfortunately, there's the same issue now with UUIDs which appear plainly in the expressions like this `(tstamp 74471dee-5f8c-4f2f-a8b3-b698196d2e19)` or the converted format from the old syntax `(tstamp 00000000-0000-0000-0000-00005eff3d45)`. The latter technically isn't a valid UUID but that's another issue.

While the easy way out would be to parse those as 128bit integers, it would need special provisions again. The least invasive change i can see would be to implement a special path in `parse_num_literal` and the symbol parsing path.

But I can imagine that that's not an option you'd want to support, it's an ugly hack.

**Comment by rotty** [comment]
@tachiniererin  Given the now much-smaller scope (support parsing the UUID syntax used), another coincidental  (implied) feature request for supporting this in #104, I've now decided to finally implement this. What pushed me over the edge was that it seems this is indeed now the only feature preventing `lexpr` to support Kicad files, as supporting this allows parsing the whole test file referenced in #104.

However, I would propose to not parse UUIDs specifically to 128-bit integers, I'd parse them as symbols, by relaxing the syntax to allow for symbols starting with a digit, when they cannot be parsed as a regular number (which should always be true for UUIDs, as they always contain a dash, in places where it would not be allowed in a number). This will be a non-default parser option, currently called `leading_digit_symbols`. I'd appreciate input regarding the option name and the feasibility of parsing the UUIDs as symbols for your use case!

**Comment by tachiniererin** [comment]
The UUIDs as symbols approach is most likely the better option just because it's also generic. For KiCad file i can't think of even a single usecase where one would want to use it as an integer (for arithmetic reasons or other) instead of as a symbol to be referenced. So yeah, :+1: to the approach and the parser option is also perfectly clear as to the intention and expected outcome imo.
