### ISSUE TITLE
`serde_lexpr::to_value()` takes `T` when `&T` would do

### ISSUE THREAD

**Issue by elidupree** [rotty/lexpr-rs#71]
The body of `to_value` does nothing but call `serde::Serialize::serialize`, which takes `&self`; thus, like other serialization methods, `to_value` should take `&T`.

**Comment by rotty** [comment]
This code is inherited from `serde_json`, which has the following comment:

> Taking by value is more friendly to iterator adapters, option and result
> consumers, etc. See https://github.com/serde-rs/json/pull/149.

In that PR, it is noted:

>  ... as there exists an implementation of `Serializable for &'a T where T: Serializable`.

I will add a similar comment in `serde_lexpr`, and then close this issue.
