### ISSUE TITLE
tuple enum with struct field missing one layer of ()

### ISSUE THREAD

**Issue by elidupree** [rotty/lexpr-rs#72]
This code:
```rust
#[derive(Debug, Serialize, Deserialize)]
struct Struct {
    field: i64,
}
#[derive(Debug, Serialize, Deserialize)]
enum Enum {
    Struct(Struct),
}

fn main() {
    println!("{}", serde_lexpr::to_string(&Struct { field: 0 }).unwrap());
    println!(
        "{}",
        serde_lexpr::to_string(&Enum::Struct(Struct { field: 0 })).unwrap()
    );
    println!(
        "{:?}",
        serde_lexpr::from_str::<Enum>("(Struct ((field.0)))")
    );
}
```
Produces the output:
```
((field . 0))
(Struct (field.0))
Err(Message("invalid type: cons cell, expected symbol", None))
```
The first line is correct; the second line should say `(Struct ((field.0)))`, thus containing the full text of the first, but it does not. The same problem exists during deserialization, giving an error when you try to deserialize the correct representation, but "successfully" deserializing the incorrect version.

Note that this incorrect representation would be the correct representation of a *struct-like variant*. Maybe some code is being incorrectly generalized between those cases?

I ran into this issue while trying to parse output from [SerAPI](https://github.com/ejgallego/coq-serapi).

**Comment by elidupree** [comment]
Looking in the code now, I see what's going on: "newtype variants" are a deliberate special case that behaves differently than other tuple-like enum variants. Perhaps this behavior could be made configurable, like the lexpr parsing options, so that it can be compatible with more types of S-expressions in the wild?

**Comment by rotty** [comment]
> ```
> ((field . 0))
>  (Struct (field.0))
> ```
> 
> The first line is correct; the second line should say `(Struct ((field.0)))`, thus containing the full text of the first, but it does not. The same problem exists during deserialization, giving an error when you try to deserialize the correct representation, but "successfully" deserializing the incorrect version.
> 
The second line can also be read as `(Struct . ((field.0)))` -- note the added dot, which gets elided in the printer/serializer.

**Comment by rotty** [comment]
As noted above, I think the output is correct, albeit the elision of the dot can be confusing.
