### ISSUE TITLE
ConsAccess always yields the same value indefinitely

### ISSUE THREAD

**Issue by elidupree** [rotty/lexpr-rs#74]
[This impl](https://github.com/rotty/lexpr-rs/blob/master/serde-lexpr/src/value/de.rs#L336-L352) never modifies `self`, resulting in an infinite loop. The tests missed this case because [ConsAccess is only constructed if you arrive at visit_seq through deserialize_any](https://github.com/rotty/lexpr-rs/blob/master/serde-lexpr/src/value/de.rs#L69) rather than [deserialize_seq](https://github.com/rotty/lexpr-rs/blob/master/serde-lexpr/src/value/de.rs#L182-L192).

**Comment by rotty** [comment]
Thanks for the report, and sorry for the delay. I can easily fix this issue, by advancing the `idx` in `ConsAccess`, but I'd like to have a unit test for that behavior. I've not yet been able to figure out how to cause serde to invoke `deserialize_any`. Do you happen to have an idea on how to achieve that?

**Comment by elidupree** [comment]
It's one of the methods that can be explicitly invoked in a `Deseralize` impl (just not often used, for [the reasons in the note in its documentation](https://docs.serde.rs/serde/de/trait.Deserializer.html#tymethod.deserialize_any)). You'll probably want to make a custom type specifically to run the tests with, something like this:

```rust
struct ConsAccessTestStruct(Vec<i32>);
struct ConsAccessTestVisitor;

impl<'de> de::Visitor<'de> for ConsAccessTestVisitor {
    type Value = ConsAccessTestStruct;
    fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        write!(formatter, "a sequence")
    }

    fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
    where
        A: de::SeqAccess<'de>,
    {
        let mut result = Vec::new();
        while let Some(element) = seq.next_element()? {
            result.push(element);
        }
        Ok(ConsAccessTestStruct(result))
    }
}

impl<'de> de::Deserialize<'de> for ConsAccessTestStruct {
    fn deserialize<D: de::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        deserializer.deserialize_any(ConsAccessTestVisitor)
    }
}
```
