### ISSUE TITLE
Evaluating Arithmetics

### ISSUE THREAD

**Issue by PabloReszczynski** [rotty/lexpr-rs#80]
Hi! First of all, thanks for this library! I've been using it for toying with a Lisp interpreter in Rust.
I have one question though, how would you recommend evaluating arithmetic operations using lexpr's Number AST?

This is what I have so far:

```rust
struct NumberType {
    n: lexpr::number::Number,
}

impl std::ops::Add for NumberType {
    type Output = NumberType;

    fn add(self, rhs: Self) -> Self::Output {
        if self.n.is_i64() && rhs.n.is_i64() {
            return NumberType {
                n: lexpr::number::Number::from(self.n.as_i64().unwrap() + rhs.n.as_i64().unwrap()),
            };
        } else if self.n.is_i64() && rhs.n.is_u64() {
            return NumberType {
                n: lexpr::number::Number::from(self.n.as_u64().unwrap() + rhs.n.as_u64().unwrap()),
            };
        } else if self.n.is_i64() && rhs.n.is_f64() {
            return NumberType {
                n: lexpr::number::Number::from(self.n.as_f64().unwrap() + rhs.n.as_f64().unwrap()),
            };
        } else {
          return rhs.add(self);
        }
    }
}
```

But I fear it is too complex, and it would have too much repeated code since I would have to redo this for each arithmetic operator.

**Comment by rotty** [comment]
An idea would be to just not use `lexpr::number::Number` for your `NumberType`, but introduce your own type, perhaps using an arbitrary-precision library like [malachite](https://www.malachite.rs/) to represent your numbers. If you want to support both floating point and integers, and the various implicit conversions, as your code snippet implies, your `NumberType` can be an enum, and you could use `match` to make the code more succint -- `lexpr`'s `Number` type is  currently opaque, as I wanted to avoid exposing its internal representation; I'm not currently inclined to change that.
